### ISSUE TITLE
Single node installation fails to create node

### ISSUE THREAD

**Issue by gioppoluca** [storageos/go-cli#131] opened 2018-07-25 15:14 UTC
Tried to create the single node testing installation.
Seems that it node has trouble.
here is the log:
```
time="2018-07-25T15:01:21Z" level=error msg="got error while listing volumes" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher=rdb
time="2018-07-25T15:01:21Z" level=error msg="got error while listing volumes" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher="dfs responder"
time="2018-07-25T15:01:21Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=1
time="2018-07-25T15:01:21Z" level=error msg="timeout accessing kv store" action=get category=client error="context deadline exceeded" key=telemetry/enabled module=store retry_count=1
time="2018-07-25T15:01:21Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=1
time="2018-07-25T15:01:21Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=1
time="2018-07-25T15:01:21Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=1
time="2018-07-25T15:01:21Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=event retry_count=1
time="2018-07-25T15:01:21Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=1
time="2018-07-25T15:01:21Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=event retry_count=1
time="2018-07-25T15:01:21Z" level=info msg=started action=watch category=client key=storageos/volumes module=store
time="2018-07-25T15:01:21Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:01:21Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:01:22Z" level=info msg="cluster leadership acquired" action=monitor category=leader module=ha
time="2018-07-25T15:01:22Z" level=info msg="leader workgroup started" action=establish category=leader module=ha
time="2018-07-25T15:01:22Z" level=info msg="started watching volumes" module=watcher
time="2018-07-25T15:01:22Z" level=info msg="started watching nodes" module=watcher
time="2018-07-25T15:01:22Z" level=info msg=started action=watch category=client key=storageos/volumes module=store
time="2018-07-25T15:01:22Z" level=info msg=started action=watch category=client key=storageos/nodes module=store
time="2018-07-25T15:02:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:02:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:03:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:03:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:03:22Z" level=info msg="revoked cluster leadership" action=revoke category=leader module=ha
time="2018-07-25T15:03:22Z" level=info msg="received stop signal" action=start category=discovery module=ha service=node version=v1
time="2018-07-25T15:03:22Z" level=info msg="received stop signal" action=start category=discovery module=ha service=node version=v1
time="2018-07-25T15:04:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:04:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:05:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:05:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:06:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:06:22Z" level=info msg="received stop signal" action=start category=watchdog module=ha
time="2018-07-25T15:06:22Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:06:22Z" level=info msg="received stop signal" action=start category=watchdog module=ha
time="2018-07-25T15:06:22Z" level=info msg="became cluster leader" action=establish category=leader module=ha
time="2018-07-25T15:06:22Z" level=info msg="leader lost lock, restarting election process" action=loop category=leader module=ha
time="2018-07-25T15:06:22Z" level=info msg="leader workgroup stopped" action=establish category=leader module=ha
time="2018-07-25T15:06:22Z" level=info msg=stopped module=watcher
time="2018-07-25T15:06:22Z" level=info msg="leader election process started" action=election category=leader module=ha
time="2018-07-25T15:06:22Z" level=info msg=stopped module=watcher
time="2018-07-25T15:06:22Z" level=warning msg="client closing session" action=watch category=client key=storageos/volumes module=store
time="2018-07-25T15:06:22Z" level=info msg=stopped action=watch category=client key=storageos/volumes module=store
time="2018-07-25T15:06:22Z" level=warning msg="volume watcher: got received error 'watch stopped'" module=watcher
time="2018-07-25T15:06:22Z" level=warning msg="client closing session" action=watch category=client key=storageos/nodes module=store
time="2018-07-25T15:06:22Z" level=info msg=stopped action=watch category=client key=storageos/nodes module=store
time="2018-07-25T15:06:22Z" level=warning msg="node watcher: got received error 'watch stopped'" module=watcher
time="2018-07-25T15:06:22Z" level=warning msg="transaction failed and etcd did not return any transaction responses" action=cad category=client key=storageos/storageos/locks/scheduler module=store
time="2018-07-25T15:06:22Z" level=error msg="failed to unlock master scheduler lock" action=revoke category=leader error="value mismatch" module=ha
time="2018-07-25T15:06:22Z" level=info msg="revoked cluster leadership" action=revoke category=leader module=ha
time="2018-07-25T15:06:22Z" level=info msg="cluster leadership acquired" action=monitor category=leader module=ha
time="2018-07-25T15:06:22Z" level=info msg="leader workgroup started" action=establish category=leader module=ha
time="2018-07-25T15:06:22Z" level=info msg="started watching volumes" module=watcher
time="2018-07-25T15:06:22Z" level=info msg="started watching nodes" module=watcher
time="2018-07-25T15:06:22Z" level=info msg="became cluster leader" action=establish category=leader module=ha
time="2018-07-25T15:06:22Z" level=info msg=started action=watch category=client key=storageos/nodes module=store
time="2018-07-25T15:06:22Z" level=info msg=started action=watch category=client key=storageos/volumes module=store
time="2018-07-25T15:07:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:07:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:08:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:08:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:09:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:09:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:10:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:10:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:11:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-25T15:11:27Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
```

Know that a single node is probably not a good option, but it should be able to run in any case, right?
Luca

**Comment by gioppoluca** [comment] 2018-07-31 13:51
Any hints on why it does not work?
Here some logs more:
'''
time="2018-07-31T09:25:42Z" level=error msg="failed to refresh lock" action=refreshlock category=client currentRefresh="2018-07-31 09:25:42.930937402 +0000 UTC m=+498862.519053958" error="context deadline exceeded" key=storageos/locks/scheduler module=store prevRefresh="2018-07-31 09:25:28.819516638 +0000 UTC m=+498848.407633197"
time="2018-07-31T09:25:42Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=0
time="2018-07-31T09:25:43Z" level=info msg="leader lost lock, restarting election process" action=loop category=leader module=ha
time="2018-07-31T09:25:43Z" level=info msg="leader workgroup stopped" action=establish category=leader module=ha
time="2018-07-31T09:25:43Z" level=info msg=stopped module=watcher
time="2018-07-31T09:25:43Z" level=warning msg="client closing session" action=watch category=client key=storageos/volumes module=store
time="2018-07-31T09:25:43Z" level=info msg=stopped action=watch category=client key=storageos/volumes module=store
time="2018-07-31T09:25:43Z" level=warning msg="volume watcher: got received error 'watch stopped'" module=watcher
time="2018-07-31T09:25:43Z" level=info msg="leader election process started" action=election category=leader module=ha
time="2018-07-31T09:25:43Z" level=info msg=stopped module=watcher
time="2018-07-31T09:25:43Z" level=warning msg="client closing session" action=watch category=client key=storageos/nodes module=store
time="2018-07-31T09:25:43Z" level=info msg=stopped action=watch category=client key=storageos/nodes module=store
time="2018-07-31T09:25:43Z" level=warning msg="node watcher: got received error 'watch stopped'" module=watcher
time="2018-07-31T09:25:46Z" level=info msg="cluster leadership acquired" action=monitor category=leader module=ha
time="2018-07-31T09:25:46Z" level=info msg="leader workgroup started" action=establish category=leader module=ha
time="2018-07-31T09:25:46Z" level=info msg="started watching volumes" module=watcher
time="2018-07-31T09:25:46Z" level=info msg="started watching nodes" module=watcher
time="2018-07-31T09:25:46Z" level=info msg=started action=watch category=client key=storageos/nodes module=store
time="2018-07-31T09:25:46Z" level=info msg=started action=watch category=client key=storageos/volumes module=store
time="2018-07-31T09:25:46Z" level=error msg="watch cancelled" action=watch category=client error="etcdserver: mvcc: required revision has been compacted" key=storageos/volumes module=store
time="2018-07-31T09:25:46Z" level=warning msg="volume watcher: got received error 'watch stopped'" module=watcher
time="2018-07-31T09:25:46Z" level=error msg="watch cancelled" action=watch category=client error="etcdserver: mvcc: required revision has been compacted" key=storageos/nodes module=store
time="2018-07-31T09:25:46Z" level=warning msg="node watcher: got received error 'watch stopped'" module=watcher
time="2018-07-31T09:25:53Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-31T09:25:53Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-31T09:26:55Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-31T09:26:55Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-31T09:27:05Z" level=error msg="got error while listing volumes" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher=rdb
time="2018-07-31T09:27:06Z" level=error msg="got error while listing presentations" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher="director presentation"
time="2018-07-31T09:27:05Z" level=error msg="got error while listing volumes" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher="dfs initiator"
time="2018-07-31T09:27:19Z" level=error msg="got error while listing volumes" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher=filesystem
time="2018-07-31T09:27:20Z" level=error msg="got error while listing volumes" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher="director volume"
time="2018-07-31T09:27:51Z" level=error msg="got error while listing presentations" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher="director presentation"
time="2018-07-31T09:27:51Z" level=error msg="got error while listing volumes" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher="director volume"
time="2018-07-31T09:27:51Z" level=error msg="got error while listing volumes" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" module=watcher watcher="dfs responder"
time="2018-07-31T09:27:52Z" level=error msg="got error while listing volumes" error="rpc error: code = DeadlineExceeded desc = Deadline Exceeded" module=watcher watcher=rdb
time="2018-07-31T09:27:53Z" level=error msg="failed to refresh lock" action=refreshlock category=client currentRefresh="2018-07-31 09:27:53.129195047 +0000 UTC m=+498992.717311636" error="context deadline exceeded" key=storageos/locks/scheduler module=store prevRefresh="2018-07-31 09:27:40.383418911 +0000 UTC m=+498979.971535507"
time="2018-07-31T09:27:55Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
'''

**Comment by gioppoluca** [comment] 2018-07-31 13:55
The OS is CentOS 7
The docker run command is:
```
docker run -d --name storageos -e HOSTNAME -e ADVERTISE_IP=10.102.81.239  -e JOIN=10.102.81.239 --pid=host --network=host --privileged --cap-add SYS_ADMIN --device /dev/fuse -v /sys:/sys -v /var/lib/storageos:/var/lib/storageos:rshared -v /run/docker/plugins:/run/docker/plugins storageos/node:1.0.0-rc3 server
```

**Comment by gioppoluca** [comment] 2018-07-31 14:04
Changed docker run command (using more recent image):
```
docker run -d --name storageos -e HOSTNAME -e ADVERTISE_IP=10.102.81.239  -e JOIN=10.102.81.239 --pid=host --net=host --privileged --cap-add SYS_ADMIN --device /dev/fuse -v /sys:/sys -v /var/lib/storageos:/var/lib/storageos:rshared -v /run/docker/plugins:/run/docker/plugins storageos/node:1.0.0-rc4 server
```
The logs now change and container dies.
```
time="2018-07-31T13:59:08Z" level=info msg="by using this product, you are agreeing to the terms of the StorageOS Ltd. End User Subscription Agreement (EUSA) found at: https://eusa.storageos.com" module=command
time="2018-07-31T13:59:08Z" level=info msg=starting address=10.102.81.239 hostname=tst-shared.pochdp.csi.it id=2a5ac821-c660-2456-050e-f26c6a020f94 join=10.102.81.239 module=command version="StorageOS 1.0.0 (0bbd203), built: 2018-07-18T163409Z"
time="2018-07-31T13:59:34Z" level=info msg="new nodes joined, initialize messaging" action=update category=nats module=cp
time="2018-07-31T13:59:35Z" level=info msg="kv store ready" action=wait address="http://127.0.0.1:5706" backend=embedded category=etcd module=cp
time="2018-07-31T13:59:35Z" level=info msg="using etcd to store encryption keys" module=command
time="2018-07-31T13:59:35Z" level=info msg="leader election process started" action=election category=leader module=ha
time="2018-07-31T13:59:37Z" level=info msg="became cluster leader" action=establish category=leader module=ha
time="2018-07-31T13:59:37Z" level=error msg="watch cancelled" action=watch category=client error="etcdserver: mvcc: required revision has been compacted" key=storageos/volumes module=store
time="2018-07-31T13:59:37Z" level=warning msg="volume watcher received error 'watch stopped'" module=watcher
time="2018-07-31T13:59:38Z" level=error msg="got error while processing volume creation event: no healthy nodes found in pool" action=volume_creation_queue category=volume_ingress module=taskrunner status=received target=
time="2018-07-31T13:59:39Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=storageos-stats release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T13:59:53Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=storageos-director release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:00:00Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=client release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:00:01Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=server release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:00:01Z" level=error msg="failed to refresh lock" action=refreshlock category=client currentRefresh="2018-07-31 14:00:01.292466025 +0000 UTC m=+53.616625346" error="context deadline exceeded" key=storageos/locks/scheduler module=store prevRefresh="0001-01-01 00:00:00 +0000 UTC"
time="2018-07-31T14:00:02Z" level=info msg="leader lost lock, restarting election process" action=loop category=leader module=ha
time="2018-07-31T14:00:03Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=0
time="2018-07-31T14:00:02Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=0
time="2018-07-31T14:00:03Z" level=info msg="leader election process started" action=election category=leader module=ha
time="2018-07-31T14:00:03Z" level=warning msg="volume watcher received error 'watch stopped'" module=watcher
time="2018-07-31T14:00:03Z" level=warning msg="node watcher received error 'watch stopped'" module=watcher
time="2018-07-31T14:00:05Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=storageos-fs-director release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:00:25Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=storageos-rdbplugin release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:00:38Z" level=error msg="failed to start dataplane services" error="dfs initiator module is not ready" module=command
```

**Comment by gioppoluca** [comment] 2018-07-31 14:10
Restarted with the option --network and not "--net" and error now seems different:
```
time="2018-07-31T14:05:34Z" level=info msg="by using this product, you are agreeing to the terms of the StorageOS Ltd. End User Subscription Agreement (EUSA) found at: https://eusa.storageos.com" module=command
time="2018-07-31T14:05:34Z" level=info msg=starting address=10.102.81.239 hostname=tst-shared.pochdp.csi.it id=2a5ac821-c660-2456-050e-f26c6a020f94 join=10.102.81.239 module=command version="StorageOS 1.0.0 (0bbd203), built: 2018-07-18T163409Z"
time="2018-07-31T14:05:58Z" level=info msg="new nodes joined, initialize messaging" action=update category=nats module=cp
time="2018-07-31T14:05:58Z" level=info msg="kv store ready" action=wait address="http://127.0.0.1:5706" backend=embedded category=etcd module=cp
time="2018-07-31T14:05:58Z" level=info msg="using etcd to store encryption keys" module=command
time="2018-07-31T14:05:58Z" level=info msg="leader election process started" action=election category=leader module=ha
time="2018-07-31T14:06:05Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=storageos-stats release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:06:21Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=server release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:06:24Z" level=error msg="failed to refresh lock" action=refreshlock category=client currentRefresh="2018-07-31 14:06:24.200360609 +0000 UTC m=+50.061839471" error="context deadline exceeded" key=storageos/locks/scheduler module=store prevRefresh="0001-01-01 00:00:00 +0000 UTC"
time="2018-07-31T14:06:24Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=0
time="2018-07-31T14:06:24Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=nodes retry_count=0
time="2018-07-31T14:06:22Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=client release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:06:25Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=storageos-director release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:06:27Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=storageos-fs-director release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:06:37Z" level=info msg="became cluster leader" action=establish category=leader module=ha
time="2018-07-31T14:06:37Z" level=info msg="leader lost lock, restarting election process" action=loop category=leader module=ha
time="2018-07-31T14:06:38Z" level=info msg="leader election process started" action=election category=leader module=ha
time="2018-07-31T14:06:40Z" level=warning msg="volume watcher received error 'watch stopped'" module=watcher
time="2018-07-31T14:06:40Z" level=warning msg="node watcher received error 'watch stopped'" module=watcher
time="2018-07-31T14:06:40Z" level=warning msg="transaction failed and etcd did not return any transaction responses" action=cad category=client key=storageos/storageos/locks/scheduler module=store
time="2018-07-31T14:06:40Z" level=error msg="failed to unlock master scheduler lock" action=revoke category=leader error="value mismatch" module=ha
time="2018-07-31T14:06:40Z" level=info msg="revoked cluster leadership" action=revoke category=leader module=ha
time="2018-07-31T14:06:40Z" level=error msg="timeout accessing kv store" action=list category=client error="context deadline exceeded" module=store prefix=pools retry_count=0
time="2018-07-31T14:06:41Z" level=info msg="became cluster leader" action=establish category=leader module=ha
time="2018-07-31T14:06:42Z" level=info msg=started.0.0.0.0-rc4_2 buildref=release/1 module=storageos-rdbplugin release=1 revision=0e119a886025b8a079c34535d7989b3ca0a772d9
time="2018-07-31T14:06:57Z" level=info msg="startup complete - ready for operation" module=command
time="2018-07-31T14:07:43Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-31T14:07:47Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-31T14:08:24Z" level=info msg="volume created" action=create category=volume module=cp name=gioppo namespace=default size=1 volume=gioppo
time="2018-07-31T14:08:46Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
time="2018-07-31T14:08:47Z" level=warning msg="node health not set or invalid, skipping update" action=defend category=watchdog endpoint=10.102.81.239 health=unknown module=ha node=tst-shared.pochdp.csi.it previous=unknown
```

**Comment by gioppoluca** [comment] 2018-07-31 14:42
When I try to create a volume it stays in "pending" status.

**Comment by gioppoluca** [comment] 2018-07-31 14:47
Here is the result of the docker run:
```
docker container run -it --volume-driver storageos --volume myvol:/data busybox sh
docker: Error response from daemon: create myvol: Post http://%2Frun%2Fdocker%2Fplugins%2Fstorageos.sock/VolumeDriver.Create: context deadline exceeded.
See 'docker run --help'.
```

Volume gets "created" and shows up in the storageos console but is in pending status

**Comment by savage-engineer** [comment] 2018-08-01 14:49
Hi @gioppoluca, thanks for getting in touch.

Although single node installations are certainly possible, we don't support installations with < 3 nodes because lack of quorum may introduce unexpected behaviour.

Please send an email to support@storageos.com to open a ticket, so that we can provide assistance. It would be useful if you could include the output of `journalctl -xu docker.service` and `docker volume ls` within it.

I'd like to close the issue here if that's ok, as this issue tracker is not the right place for installation troubleshooting.

**Closed** 2018-08-03 08:40 UTC
